first_name = input("What is your first name? ")
last_name = input("What is your last name? ")
email = input("What is your email adress? ")
phone = input("What is your phone number? ")
job_title  = input("What is your job  title? ")
id_number  = input("What is your id number? ")
hair_color  = input("What is your hair color? ")
eye_color = input("What is your eye color? ")
start_month =  input("When did you start? ")
advanced_training = input("Have you completed advanced training? yes/no ")

print("-----------------------------------")
print(f"{last_name.upper()}, {first_name.capitalize()}")
print(job_title.title())
print(f"ID: ", id_number)
print()
print(email.lower())
print(phone)
print(f"Hair: {hair_color:15} Eyes: {eye_color}")
print(f"Month: {start_month:14} Training: {advanced_training.capitalize()}")
print("-----------------------------------")