adjective1 = input("Enter an adjective: ")
adjective2 = input("Enter another adjective: ")
noun1 = input("Enter a noun: ")
noun2 = input("Enter another noun: ")
verb1 = input("Enter a verb: ")
verb2 = input("Enter another verb: ")

print("The " + adjective1 + " fox was feeling very " + adjective2 + " today.")
print("It wanted to go for a walk and explore the " + noun1 + ".")
print("So it " + verb1 + " out of its cozy den and into the bright sunshine.")
print("As it wandered through the forest, it came across a " + noun2 + ".")
print("The fox was so fascinated by the " + noun2 + " that it couldn't resist the urge to " + verb2 + " it.")
print("After a few minutes, the fox realized it had been " + verb2 + " for quite some time and decided to head back home.")
print("As it " + verb1 + " back through the forest, it couldn't wait to tell all of its fox friends about its exciting adventure.")
